### ISSUE TITLE
Статус готовности отчёта

### ISSUE THREAD

**Issue by 3dsoundfromtagan** [snegovskaya/gvandra2024#3]
Что осталось сделать по техническим описаниям:
@3dsoundfromtagan Завершить описания и подготовить их к проверке Дашей:
- [x] 18 августа
- [x] 19 августа
- [x] 20 августа
- [x] 21 августа
- [x] 22 августа
- [x] 23 августа
- [x] 24 августа
- [x] 25 августа
- [x] 26 августа
- [x] 27 августа
- [x] 28 августа
- [x] 29 августа
- [x] 30 августа

@snegovskaya Чекнуть и, возможно, отредачить дни:
- [x] 18 августа
- [x] 19 августа
- [x] 20 августа
- [x] 21 августа
- [x] 22 августа
- [x] 23 августа
- [x] 24 августа
- [x] 25 августа
- [x] 26 августа
- [x] 27 августа
- [x] 28 августа
- [x] 29 августа
- [x] 30 августа

@3dsoundfromtagan Добавить долбанные мной таблички
- [x] Уллу-Кёль Вост.
- [x] Джалпаккол Сев.
- [x] Кичкинекол Вост.
- [x] Перемётный
- [x] Хотютау

**Comment by snegovskaya** [comment]
Как там с готовностью отчёта обстоит вопрос?

**Comment by snegovskaya** [comment]
Осталось: 
- [x] Поправить чёртов смайлик и библиографию;  
- [x] 24-е: поменять время с настоящего на прошедшее и описать сход Георгия; 
- [x] 27-е: отредачить первую половину (подъём на Перемётный) и вывод; 
- [x] 30-е: время посадки на канатную дорогу; 
- [x] 27-е: Добавить скрины с Google Earth; 

@3dsoundfromtagan Раздел про карты и материалы.
